// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADL5MAlLmcXZQOxNDVKdD_VJs-XH3PJJo',
    appId: '1:150034354731:web:54c828b6687887000ad06e',
    messagingSenderId: '150034354731',
    projectId: 'agriconnectchatapp',
    authDomain: 'agriconnectchatapp.firebaseapp.com',
    databaseURL: 'https://agriconnectchatapp-default-rtdb.firebaseio.com',
    storageBucket: 'agriconnectchatapp.firebasestorage.app',
    measurementId: 'G-NCF4GH2LBS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5Mf6bhWruHfcNQxH4iaEVir_zNgwwSbw',
    appId: '1:150034354731:android:3a1ea01acfa5dcb60ad06e',
    messagingSenderId: '150034354731',
    projectId: 'agriconnectchatapp',
    databaseURL: 'https://agriconnectchatapp-default-rtdb.firebaseio.com',
    storageBucket: 'agriconnectchatapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCk4kcIy1xtz6ZFELVqBiA0IdctcJx2YZI',
    appId: '1:150034354731:ios:2f1455b2020990d90ad06e',
    messagingSenderId: '150034354731',
    projectId: 'agriconnectchatapp',
    databaseURL: 'https://agriconnectchatapp-default-rtdb.firebaseio.com',
    storageBucket: 'agriconnectchatapp.firebasestorage.app',
    iosBundleId: 'com.example.agriconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCk4kcIy1xtz6ZFELVqBiA0IdctcJx2YZI',
    appId: '1:150034354731:ios:2f1455b2020990d90ad06e',
    messagingSenderId: '150034354731',
    projectId: 'agriconnectchatapp',
    databaseURL: 'https://agriconnectchatapp-default-rtdb.firebaseio.com',
    storageBucket: 'agriconnectchatapp.firebasestorage.app',
    iosBundleId: 'com.example.agriconnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADL5MAlLmcXZQOxNDVKdD_VJs-XH3PJJo',
    appId: '1:150034354731:web:ac068f08cb1951250ad06e',
    messagingSenderId: '150034354731',
    projectId: 'agriconnectchatapp',
    authDomain: 'agriconnectchatapp.firebaseapp.com',
    databaseURL: 'https://agriconnectchatapp-default-rtdb.firebaseio.com',
    storageBucket: 'agriconnectchatapp.firebasestorage.app',
    measurementId: 'G-HCCCMC8ELE',
  );
}
